"""new fields in user model

Revision ID: 393cebeac1eb
Revises: 0888f4a5df09
Create Date: 2018-09-19 13:10:41.629406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393cebeac1eb'
down_revision = '0888f4a5df09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
